# Generated by Django 3.2.9 on 2021-11-05 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('adviser_id', models.AutoField(primary_key=True, serialize=False)),
                ('adviser_name', models.CharField(max_length=100, unique=True)),
                ('adviser_photo', models.FileField(blank=True, null=True, upload_to='booking_user/adviser_pics/')),
                ('adviser_photo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_user.adviser')),
            ],
        ),
    ]
